/**
 * Left-hand navigation configuration for Sovereign Intelligence Platform.
 * Order matches production: Overview → … → Administration.
 */

export interface NavItem {
  id: string;
  label: string;
  path: string;
  children?: { id: string; label: string; path: string }[];
}

export const navConfig: NavItem[] = [
  {
    id: "overview",
    label: "Overview",
    path: "/overview",
    children: [
      { id: "executive-dashboard", label: "Executive Dashboard", path: "/overview/executive-dashboard" },
      { id: "sovereignty-overview", label: "Sovereignty Overview", path: "/overview/sovereignty-overview" },
      { id: "data-ai-maturity-overview", label: "Data & AI Maturity Overview", path: "/overview/data-ai-maturity-overview" },
      { id: "national-intelligence-summary", label: "National Intelligence Summary", path: "/overview/national-intelligence-summary" },
      { id: "recent-alerts-changes", label: "Recent Alerts & Changes", path: "/overview/recent-alerts-changes" },
    ],
  },
  {
    id: "organisations",
    label: "Organisations",
    path: "/organisations",
    children: [
      { id: "all-organisations", label: "All Organisations", path: "/organisations/all" },
      { id: "organisation-explorer", label: "Organisation Explorer", path: "/organisations/explorer" },
      { id: "sovereignty-assessments", label: "Sovereignty Assessments", path: "/organisations/sovereignty-assessments" },
      { id: "data-maturity-assessments", label: "Data Maturity Assessments", path: "/organisations/data-maturity-assessments" },
      { id: "ai-maturity-assessments", label: "AI Maturity Assessments", path: "/organisations/ai-maturity-assessments" },
      { id: "organisation-risk-profiles", label: "Organisation Risk Profiles", path: "/organisations/risk-profiles" },
      { id: "audit-history", label: "Audit History", path: "/organisations/audit-history" },
      { id: "add-organisation", label: "Add Organisation", path: "/organisations/add" },
    ],
  },
  {
    id: "sovereignty-intelligence",
    label: "Sovereignty Intelligence",
    path: "/sovereignty-intelligence",
    children: [
      { id: "sovereignty-dashboard", label: "Sovereignty Dashboard", path: "/sovereignty-intelligence/dashboard" },
      { id: "sovereignty-scores", label: "Sovereignty Scores", path: "/sovereignty-intelligence/scores" },
      { id: "vendor-dependency-analysis", label: "Vendor Dependency Analysis", path: "/sovereignty-intelligence/vendor-dependency" },
      { id: "vendor-concentration-risk", label: "Vendor Concentration Risk", path: "/sovereignty-intelligence/vendor-concentration" },
      { id: "exit-feasibility-analysis", label: "Exit Feasibility Analysis", path: "/sovereignty-intelligence/exit-feasibility" },
      { id: "jurisdiction-residency-analysis", label: "Jurisdiction & Residency Analysis", path: "/sovereignty-intelligence/jurisdiction-residency" },
      { id: "identity-sovereignty", label: "Identity Sovereignty", path: "/sovereignty-intelligence/identity" },
      { id: "infrastructure-sovereignty", label: "Infrastructure Sovereignty", path: "/sovereignty-intelligence/infrastructure" },
      { id: "content-sovereignty", label: "Content Sovereignty", path: "/sovereignty-intelligence/content" },
      { id: "supply-chain-sovereignty", label: "Supply Chain Sovereignty", path: "/sovereignty-intelligence/supply-chain" },
    ],
  },
  {
    id: "data-intelligence",
    label: "Data Intelligence",
    path: "/data-intelligence",
    children: [
      { id: "data-maturity-dashboard", label: "Data Maturity Dashboard", path: "/data-intelligence/dashboard" },
      { id: "data-maturity-scores", label: "Data Maturity Scores", path: "/data-intelligence/scores" },
      { id: "data-infrastructure-analysis", label: "Data Infrastructure Analysis", path: "/data-intelligence/infrastructure" },
      { id: "data-governance-analysis", label: "Data Governance Analysis", path: "/data-intelligence/governance" },
      { id: "data-platform-inventory", label: "Data Platform Inventory", path: "/data-intelligence/platform-inventory" },
      { id: "data-quality-monitoring", label: "Data Quality Monitoring", path: "/data-intelligence/quality-monitoring" },
      { id: "data-sovereignty-analysis", label: "Data Sovereignty Analysis", path: "/data-intelligence/sovereignty-analysis" },
    ],
  },
  {
    id: "ai-intelligence",
    label: "AI Intelligence",
    path: "/ai-intelligence",
    children: [
      { id: "ai-maturity-dashboard", label: "AI Maturity Dashboard", path: "/ai-intelligence/dashboard" },
      { id: "ai-capability-scores", label: "AI Capability Scores", path: "/ai-intelligence/scores" },
      { id: "ai-deployment-inventory", label: "AI Deployment Inventory", path: "/ai-intelligence/deployment-inventory" },
      { id: "ai-risk-analysis", label: "AI Risk Analysis", path: "/ai-intelligence/risk-analysis" },
      { id: "ai-operational-integration", label: "AI Operational Integration", path: "/ai-intelligence/operational-integration" },
      { id: "ai-opportunity-analysis", label: "AI Opportunity Analysis", path: "/ai-intelligence/opportunity-analysis" },
      { id: "ai-investment-recommendations", label: "AI Investment Recommendations", path: "/ai-intelligence/investment-recommendations" },
    ],
  },
  {
    id: "technology-stack",
    label: "Technology Stack",
    path: "/technology-stack",
    children: [
      { id: "technology-inventory", label: "Technology Inventory", path: "/technology-stack/inventory" },
      { id: "vendor-registry", label: "Vendor Registry", path: "/technology-stack/vendor-registry" },
      { id: "cloud-infrastructure", label: "Cloud Infrastructure", path: "/technology-stack/cloud" },
      { id: "databases", label: "Databases", path: "/technology-stack/databases" },
      { id: "identity-providers", label: "Identity Providers", path: "/technology-stack/identity-providers" },
      { id: "devops-infrastructure", label: "DevOps & Infrastructure", path: "/technology-stack/devops" },
      { id: "messaging-systems", label: "Messaging Systems", path: "/technology-stack/messaging" },
      { id: "observability-tools", label: "Observability Tools", path: "/technology-stack/observability" },
      { id: "software-dependencies", label: "Software Dependencies", path: "/technology-stack/dependencies" },
    ],
  },
  {
    id: "content-data-assets",
    label: "Content & Data Assets",
    path: "/content-data-assets",
    children: [
      { id: "content-asset-registry", label: "Content Asset Registry", path: "/content-data-assets/content-registry" },
      { id: "data-asset-registry", label: "Data Asset Registry", path: "/content-data-assets/data-registry" },
      { id: "content-sovereignty-scores", label: "Content Sovereignty Scores", path: "/content-data-assets/content-sovereignty-scores" },
      { id: "data-ownership-analysis", label: "Data Ownership Analysis", path: "/content-data-assets/data-ownership" },
      { id: "jurisdiction-analysis", label: "Jurisdiction Analysis", path: "/content-data-assets/jurisdiction-analysis" },
      { id: "intellectual-property-registry", label: "Intellectual Property Registry", path: "/content-data-assets/ip-registry" },
    ],
  },
  {
    id: "infrastructure-assets",
    label: "Infrastructure & Assets",
    path: "/infrastructure-assets",
    children: [
      { id: "infrastructure-dashboard", label: "Infrastructure Dashboard", path: "/infrastructure-assets/dashboard" },
      { id: "data-centres", label: "Data Centres", path: "/infrastructure-assets/data-centres" },
      { id: "cloud-regions", label: "Cloud Regions", path: "/infrastructure-assets/cloud-regions" },
      { id: "critical-infrastructure-assets", label: "Critical Infrastructure Assets", path: "/infrastructure-assets/critical" },
      { id: "telecom-infrastructure", label: "Telecom Infrastructure", path: "/infrastructure-assets/telecom" },
      { id: "physical-infrastructure-registry", label: "Physical Infrastructure Registry", path: "/infrastructure-assets/physical-registry" },
    ],
  },
  {
    id: "geographic-intelligence",
    label: "Geographic Intelligence",
    path: "/geographic-intelligence",
    children: [
      { id: "countries", label: "Countries", path: "/geographic-intelligence/countries" },
      { id: "cities", label: "Cities", path: "/geographic-intelligence/cities" },
      { id: "regions", label: "Regions", path: "/geographic-intelligence/regions" },
      { id: "national-sovereignty-index", label: "National Sovereignty Index", path: "/geographic-intelligence/national-index" },
      { id: "city-sovereignty-scores", label: "City Sovereignty Scores", path: "/geographic-intelligence/city-scores" },
      { id: "regional-capability-scores", label: "Regional Capability Scores", path: "/geographic-intelligence/regional-scores" },
      { id: "geographic-risk-analysis", label: "Geographic Risk Analysis", path: "/geographic-intelligence/risk-analysis" },
    ],
  },
  {
    id: "sector-intelligence",
    label: "Sector Intelligence",
    path: "/sector-intelligence",
    children: [
      { id: "sector-dashboard", label: "Sector Dashboard", path: "/sector-intelligence/dashboard" },
      { id: "energy", label: "Energy", path: "/sector-intelligence/energy" },
      { id: "finance", label: "Finance", path: "/sector-intelligence/finance" },
      { id: "healthcare", label: "Healthcare", path: "/sector-intelligence/healthcare" },
      { id: "transport", label: "Transport", path: "/sector-intelligence/transport" },
      { id: "communications", label: "Communications", path: "/sector-intelligence/communications" },
      { id: "government", label: "Government", path: "/sector-intelligence/government" },
      { id: "technology", label: "Technology", path: "/sector-intelligence/technology" },
      { id: "manufacturing", label: "Manufacturing", path: "/sector-intelligence/manufacturing" },
      { id: "sector-risk-analysis", label: "Sector Risk Analysis", path: "/sector-intelligence/risk-analysis" },
    ],
  },
  {
    id: "dependency-graph",
    label: "Dependency Graph",
    path: "/dependency-graph",
    children: [
      { id: "global-dependency-graph", label: "Global Dependency Graph", path: "/dependency-graph/global" },
      { id: "organisation-dependency-graph", label: "Organisation Dependency Graph", path: "/dependency-graph/organisation" },
      { id: "vendor-dependency-graph", label: "Vendor Dependency Graph", path: "/dependency-graph/vendor" },
      { id: "infrastructure-dependency-graph", label: "Infrastructure Dependency Graph", path: "/dependency-graph/infrastructure" },
      { id: "jurisdiction-exposure-graph", label: "Jurisdiction Exposure Graph", path: "/dependency-graph/jurisdiction-exposure" },
    ],
  },
  {
    id: "risk-simulation",
    label: "Risk & Simulation",
    path: "/risk-simulation",
    children: [
      { id: "risk-dashboard", label: "Risk Dashboard", path: "/risk-simulation/dashboard" },
      { id: "vendor-lock-in-risk", label: "Vendor Lock-in Risk", path: "/risk-simulation/vendor-lock-in" },
      { id: "jurisdiction-risk", label: "Jurisdiction Risk", path: "/risk-simulation/jurisdiction-risk" },
      { id: "systemic-risk-analysis", label: "Systemic Risk Analysis", path: "/risk-simulation/systemic-risk" },
      { id: "failure-simulation", label: "Failure Simulation", path: "/risk-simulation/failure-simulation" },
      { id: "exit-simulation", label: "Exit Simulation", path: "/risk-simulation/exit-simulation" },
      { id: "concentration-risk-analysis", label: "Concentration Risk Analysis", path: "/risk-simulation/concentration-risk" },
    ],
  },
  {
    id: "reports-intelligence",
    label: "Reports & Intelligence",
    path: "/reports-intelligence",
    children: [
      { id: "executive-reports", label: "Executive Reports", path: "/reports-intelligence/executive" },
      { id: "organisation-reports", label: "Organisation Reports", path: "/reports-intelligence/organisation" },
      { id: "sector-reports", label: "Sector Reports", path: "/reports-intelligence/sector" },
      { id: "national-reports", label: "National Reports", path: "/reports-intelligence/national" },
      { id: "sovereignty-reports", label: "Sovereignty Reports", path: "/reports-intelligence/sovereignty" },
      { id: "audit-reports", label: "Audit Reports", path: "/reports-intelligence/audit" },
      { id: "export-center", label: "Export Center", path: "/reports-intelligence/export" },
    ],
  },
  {
    id: "alerts-monitoring",
    label: "Alerts & Monitoring",
    path: "/alerts-monitoring",
    children: [
      { id: "alerts-dashboard", label: "Alerts Dashboard", path: "/alerts-monitoring/dashboard" },
      { id: "sovereignty-alerts", label: "Sovereignty Alerts", path: "/alerts-monitoring/sovereignty" },
      { id: "vendor-dependency-alerts", label: "Vendor Dependency Alerts", path: "/alerts-monitoring/vendor-dependency" },
      { id: "infrastructure-changes", label: "Infrastructure Changes", path: "/alerts-monitoring/infrastructure-changes" },
      { id: "ai-deployment-changes", label: "AI Deployment Changes", path: "/alerts-monitoring/ai-deployment-changes" },
      { id: "data-location-changes", label: "Data Location Changes", path: "/alerts-monitoring/data-location-changes" },
    ],
  },
  {
    id: "audit-evidence",
    label: "Audit & Evidence",
    path: "/audit-evidence",
    children: [
      { id: "audit-log", label: "Audit Log", path: "/audit-evidence/audit-log" },
      { id: "evidence-registry", label: "Evidence Registry", path: "/audit-evidence/evidence-registry" },
      { id: "source-documents", label: "Source Documents", path: "/audit-evidence/source-documents" },
      { id: "assessment-history", label: "Assessment History", path: "/audit-evidence/assessment-history" },
      { id: "confidence-scores", label: "Confidence Scores", path: "/audit-evidence/confidence-scores" },
    ],
  },
  {
    id: "agents-automation",
    label: "Agents & Automation",
    path: "/agents-automation",
    children: [
      { id: "agent-dashboard", label: "Agent Dashboard", path: "/agents-automation/dashboard" },
      { id: "source-discovery-agents", label: "Source Discovery Agents", path: "/agents-automation/source-discovery" },
      { id: "document-ingestion-agents", label: "Document Ingestion Agents", path: "/agents-automation/document-ingestion" },
      { id: "stack-inference-agents", label: "Stack Inference Agents", path: "/agents-automation/stack-inference" },
      { id: "scoring-agents", label: "Scoring Agents", path: "/agents-automation/scoring" },
      { id: "automation-settings", label: "Automation Settings", path: "/agents-automation/settings" },
    ],
  },
  {
    id: "administration",
    label: "Administration",
    path: "/administration",
    children: [
      { id: "users-permissions", label: "Users & Permissions", path: "/administration/users" },
      { id: "roles", label: "Roles", path: "/administration/roles" },
      { id: "organisation-settings", label: "Organisation Settings", path: "/administration/organisation-settings" },
      { id: "scoring-configuration", label: "Scoring Configuration", path: "/administration/scoring-config" },
      { id: "vendor-registry-management", label: "Vendor Registry Management", path: "/administration/vendor-registry" },
      { id: "integration-settings", label: "Integration Settings", path: "/administration/integrations" },
      { id: "api-keys", label: "API Keys", path: "/administration/api-keys" },
    ],
  },
];
